In [2]:
# First we impot plotly's figure factory
import plotly.figure_factory as ff

import numpy as np
import pandas as pd

# Load our data
df_sample = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/laucnty16.csv')
df_sample.head()

,LAUS Code,State FIPS Code,County FIPS Code,County Name/State Abbreviation,Year,Labor Force,Employed,Unemployed,Unemployment Rate (%)
0,CN0100100000000,1,1,"Autauga County, AL",2016,"25,649","24,297","1,352",5.3
1,CN0100300000000,1,3,"Baldwin County, AL",2016,"89,931","85,061","4,870",5.4
2,CN0100500000000,1,5,"Barbour County, AL",2016,"8,302","7,584",718,8.6
3,CN0100700000000,1,7,"Bibb County, AL",2016,"8,573","8,004",569,6.6
4,CN0100900000000,1,9,"Blount County, AL",2016,"24,525","23,171","1,354",5.5

In [3]:
fig = ff.create_choropleth(
    fips=fips,
    values=values,
    scope=['usa'],
    binning_endpoints=endpts,
    colorscale=colorscale,
    show_state_data=False,
    show_hover=True,
    asp = 2.9, # aspectratio
    title_text = 'USA by Unemployment %',
    legend_title = '% unemployed'
)
fig.layout.template = None
fig.show()

NameError: name 'fips' is not defined